### ISSUE TITLE
ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by scottzirkel** [Homebrew/homebrew-services#11]
Not 100% this is a services issue, but I have stripped down and reinstalled  brew, ruby and more and it's still doing it. 

When I run `brew services start (mysql|httpd22)` I get the following error:

````
Error: ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
Extracting libxml2-2.8.0.tar.gz into tmp/x86_64-apple-darwin14.3.0/ports/libxml2/2.8.0... OK
Running 'compile' for libxml2 2.8.0... ERROR, review 'tmp/x86_64-apple-darwin14.3.0/ports/libxml2/2.8.0/compile.log' to see what happened.
/Library/Ruby/Gems/2.0.0/gems/mini_portile-0.5.2/lib/mini_portile.rb:265:in `block in execute': Failed to complete compile task (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/mini_portile-0.5.2/lib/mini_portile.rb:257:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/mini_portile-0.5.2/lib/mini_portile.rb:257:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/mini_portile-0.5.2/lib/mini_portile.rb:69:in `compile'
	from /Library/Ruby/Gems/2.0.0/gems/mini_portile-0.5.2/lib/mini_portile.rb:109:in `cook'
	from extconf.rb:101:in `block in <main>'
	from extconf.rb:119:in `call'
	from extconf.rb:119:in `block in <main>'
	from extconf.rb:109:in `tap'
	from extconf.rb:109:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/nokogiri-1.6.1 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/nokogiri-1.6.1/gem_make.out
````

I am not using system Ruby or the system gempath, yet this keeps referencing gems in the system gem path. It mentions nokogiri but I don't use that nor have it installed.

My $PATH, which you can see sets the correct ruby path:
````
/Users/scott/.rvm/gems/ruby-2.2.2/bin:/Users/scott/.rvm/gems/ruby-2.2.2@global/bin:/Users/scott/.rvm/rubies/ruby-2.2.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/Users/scott/.rvm/bin:/Users/scott/.npm-packages/bin:/usr/local/sbin:/Users/scott/.rvm/bin
````

**Comment by scottzirkel** [comment]
Fixed it with Homebrew/homebrew#31220

**Comment by pmutua** [comment]
I have this problem on my linux OS:
```
Building native extensions.  This could take a while...
ERROR:  Error installing rails:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/nokogiri-1.8.1/ext/nokogiri
/usr/bin/ruby2.3 -r ./siteconf20171120-5536-amlck4.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/nokogiri-1.8.1 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.8.1/gem_make.out
```

How do I fix this issue from the logs?

**Comment by ilovezfs** [comment]
This is Homebrew not Linuxbrew.
