### ISSUE TITLE
Warning: Calling Tty.white is deprecated!

### ISSUE THREAD

**Issue by aheckler** [Homebrew/homebrew-services#115]
Running `brew services list` shows me this error:

```
Pro: ~ $ brew services list
Warning: Calling Tty.white is deprecated!
Use Tty.reset.bold instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:173:in `list'
Please report this to the homebrew/services tap!

Name    Status  User Plist
httpd24 stopped
mariadb stopped
nginx   stopped
php71   stopped
```

Couldn't find an existing report of this anywhere.

**Comment by whalesalad** [comment]
I am also experiencing the same issue.

```
brew services list
Error: Calling Tty.white is disabled!
Use Tty.reset.bold instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:241:in `list'
Please report this to the homebrew/services tap!
Or, even better, submit a PR to fix it!
```
