### ISSUE TITLE
Warning: Calling fails_with :llvm is deprecated!

### ISSUE THREAD

**Issue by Maples7** [Homebrew/homebrew-services#131]
When I run `brew services list`, a few warnings occurs here:

```sh
➜  ~ brew services list
Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:86:in `available_services'
Please report this to the homebrew/services tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:86:in `available_services'
Please report this to the homebrew/services tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:86:in `available_services'
Please report this to the homebrew/services tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:86:in `available_services'
Please report this to the homebrew/services tap!

Name       Status  User    Plist
mongodb    stopped
mysql      stopped
postgresql stopped
```

How can I stop the warning?

**Comment by MikeMcQuaid** [comment]
Figure out which formula you have installed is using these deprecated methods and uninstall it.

**Comment by Maples7** [comment]
@MikeMcQuaid Problem solved! Thx! :D

**Comment by haroldrandom** [comment]
@Maples7 How do you fix it?

**Comment by Maples7** [comment]
@haroldrandom just as @MikeMcQuaid said, uninstall bad useless formulas.
