### ISSUE TITLE
Bash completion breaks Homebrew tests

### ISSUE THREAD

**Issue by amyspark** [Homebrew/homebrew-services#141]
Since commit https://github.com/Homebrew/homebrew-services/commit/c4ccddf2f635122599c759c87813f95da2488828 , all Travis builds fail because of `brew tests`:
```
amalia@Sakura:~/Desktop/homebrew-sandbox$ brew tests --online --only=cmd/services
1 processes for 1 specs, ~ 1 specs per process

Randomized with seed 9964
F

Failures:

  1) brew services allows controlling services
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
     
       file leak detected:
         /prefix/etc
         /prefix/etc/bash_completion.d
         /prefix/etc/bash_completion.d/_brew_services
       #<RSpec::Core::Example::Procsy:0x00000102288cc0>
     # ./test/spec_helper.rb:138:in `block (2 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block (2 levels) in <top (required)>'

Finished in 3.45 seconds (files took 1.11 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./test/cmd/services_spec.rb:2 # brew services allows controlling services

Randomized with seed 9964


1 example, 1 failure

Took 4 seconds
Tests Failed
```

**Comment by MikeMcQuaid** [comment]
Thanks for the issue but this is in progress in https://github.com/Homebrew/brew/pull/3424; please check out open PRs to check these sort of things aren't already in progress.

**Comment by MikeMcQuaid** [comment]
Fixed in https://github.com/Homebrew/brew/pull/3424.
