### ISSUE TITLE
Warning: Calling 'depends_on :hg' is deprecated!

### ISSUE THREAD

**Issue by m-o-e** [Homebrew/homebrew-services#147]
`brew services list` gives me the following warning:

> Warning: Calling 'depends_on :hg' is deprecated!
Use 'depends_on "mercurial"' instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:86:in `available_services'
Please report this to the homebrew/services tap!

**Comment by MikeMcQuaid** [comment]
what's the full output of that command for you as well as `brew list` and `brew tap`? Thanks!

**Comment by m-o-e** [comment]
```
$ brew services list
Warning: Calling 'depends_on :hg' is deprecated!
Use 'depends_on "mercurial"' instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:86:in `available_services'
Please report this to the homebrew/services tap!

Name       Status  User Plist
postgresql started moe  /Users/moe/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
redis      started moe  /Users/moe/Library/LaunchAgents/homebrew.mxcl.redis.plist
...
```

```
$ brew list
ack			encfs			harfbuzz		liblwgeom		neovim			ruby-build
apple-gcc42		erlang			heroku			libmpc			netperf			s3cmd
argp-standalone		faac			heroku-node		libogg			ngrep			samba
autocode		fasd			htop			libpng			ngrok			sfcgal
autoconf		fdk-aac			htop-osx		libpq			nmap			shellcheck
automake		fdk-aac-encoder		httpie			libspatialite		node			sl
aws-elasticbeanstalk	ffmpeg			hub			libssh			nvm			sqlite
awscli			findutils		hugo			libtiff			objective-caml		stow
bash			fish			hunspell		libtool			oniguruma		switchaudio-osx
bash-completion		flac			icu4c			libusb			openssl			tesseract
bash-git-prompt		flock			id3lib			libusb-compat		parallel		texi2html
bats			fontconfig		id3v2			libvorbis		patchutils		the_silver_searcher
bchunk			fortune			iftop			libvpx			pcre			tmate
bdw-gc			freetype		imagemagick		libxdiff		pdsh			tmux
bfg			freexl			influxdb		libxml2			perl			tree
blueutil		fribidi			iniparser		libyaml			pgcli			unison
boost			fuse4x			intltool		libyubikey		phantomjs		unrar
brew-gem		fuse4x-kext		iperf			little-cms		pinentry		v8
bsdiff			gcc			isl			little-cms2		pixman			v8-315
cairo			gdal			jasper			llvm			pkg-config		v8@3.15
cgal			gdbm			jpeg			lmdb			postgresql		vapoursynth
check			geoip			jq			log4c			proctools		vim
cloc			geos			json-c			lua			proj			watch
cmake			gettext			jsonpp			lzip			protobuf		wget
colordiff		giflib			lame			lzlib			pstree			wrk
coreutils		gifsicle		lcdproc			makedepend		pth			wxmac
cowsay			git			leptonica		maven			pwgen			x264
crystal-lang		git-flow		lftp			media-info		pyenv			xvid
csync			git-flow-avh		libass			mercurial		python			xz
ctop			git-lfs			libassuan		mitmproxy		python3			yajl
curl			glib			libav			mmv			q			yarn
dialog			gmp			libevent		mobile-shell		randomize-lines		yasm
diff-so-fancy		gnu-getopt		libffi			mosh			rbenv			ykpers
direnv			gnu-tar			libftdi0		mp3info			readline		youtube-dl
dirmngr			go			libgcrypt		mpfr			redis			yubico-piv-tool
dnstop			gobject-introspection	libgeotiff		mpv			renameutils		zimg
doctl			gpg-agent		libgpg-error		msgpack			ripgrep			zsh
docutils		graphicsmagick		libhid			mtr			rlog
elixir			gzrt			libksba			nasm			ruby
```
```
$ brew tap
caskroom/cask
caskroom/versions
codeclimate/formulae
discoteq/discoteq
ethereum/ethereum
heroku/brew
homebrew/boneyard
homebrew/core
homebrew/dupes
homebrew/fuse
homebrew/services
homebrew/versions
neovim/neovim
paritytech/paritytech
```

**Comment by ilovezfs** [comment]
What's the output of
```
find $(brew --cellar) -maxdepth 4 -mindepth 4 -regex '.*\.rb$' -exec grep -r 'depends_on :hg' "{}" \;
```

**Comment by m-o-e** [comment]
Interesting!

```
/usr/local/Cellar/ngrok/1.7.1_1/.brew/ngrok.rb:  depends_on :hg => :build
```

So it was unrelated to _brew-services_ after all.
`brew uninstall ngrok` fixed it for me.

Thanks for helping and sorry for the noise!
(I just followed the on-screen instructions ¯\\\_(ツ)\_/¯)
