### ISSUE TITLE
Error: NaN when trying to do brew services list

### ISSUE THREAD

**Issue by oniofchaos** [Homebrew/homebrew-services#162]
```
Dillons-MacBook-Pro:q-centrix dillonwelch$ brew services list
Error: NaN
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:152:in `to_i'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:152:in `detect_version_from_clang_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:144:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:114:in `version'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/phantomjs.rb:17:in `<class:Phantomjs>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/phantomjs.rb:1:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:46:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:101:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:239:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:92:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:229:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:311:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:294:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1399:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1397:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1397:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1397:in `installed'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:77:in `available_services'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:121:in `list'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:102:in `run!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:516:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:18:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

**Comment by oniofchaos** [comment]
Did a `brew install x` and that updated homebrew which ended up fixing this problem.
