### ISSUE TITLE
running sudo brew services gives a traceback and doesn't work.

### ISSUE THREAD

**Issue by bryceml** [Homebrew/homebrew-services#202]
When I run:
```bash
sudo brew services restart filebeat-full
```
I get:
```
Error: undefined method `first' for nil:NilClass
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:343:in `block in start'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:318:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:318:in `start'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:245:in `block in restart'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:237:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:237:in `restart'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:117:in `run!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:578:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:82:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:108:in `<main>'
```

There is similar output for start as well.

**Comment by MikeMcQuaid** [comment]
@bryceml That's not a formula in Homebrew/core and it has invalid syntax that needs to be fixed for `brew services` to work correctly. I will close this with a pull request that will handle this error but you need to report this to wherever you got that formula from.
