### ISSUE TITLE
Can't use any sub command in brew services

### ISSUE THREAD

**Issue by evileyecc1** [Homebrew/homebrew-services#216]
Try use any command but get an error.Can't search any releated question about it.

Error:
```
[root@StarSky /usr/local/nginx]$:brew services list
Error: private method `named' called for ["list"]:Array
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:103:in `run!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:539:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:81:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:112:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
`brew update --force` and try again. If that doesn't work: `brew update-reset` and try again.
