### ISSUE TITLE
Error: undefined method `named' for #<OptionParser:0x00007fce6d2a6258>

### ISSUE THREAD

**Issue by phpjungle** [Homebrew/homebrew-services#251]
$ brew services list
Error: undefined method `named' for #<OptionParser:0x00007fce6d2a6258>
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:65:in `run!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:48:in `services'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'

**Comment by phpjungle** [comment]
I reinstall homebrew , ok is now 😁
