### ISSUE TITLE
Undefined method `boot_path_plist_present?'

### ISSUE THREAD

**Issue by Jacobfaib** [Homebrew/homebrew-services#345]
My specific error message:
-----------
```
Error: undefined method `boot_path_plist_present?' for #<Homebrew::Service:0x00007fe5a31a2d28>
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service.rb:86:in `plist_present?'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:206:in `block in restart'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:205:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:205:in `restart'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:92:in `run!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:48:in `services'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

How to reproduce:
-------
```
brew services restart [FORMULA]
```

Version info
--------
macOS Big Sur v 11.4
```
$ brew --version
Homebrew 3.1.9
Homebrew/homebrew-core (git revision fcc15b1593; last commit 2021-05-31)
Homebrew/homebrew-cask (git revision 6525a5b1e3; last commit 2021-05-31)

$ uname -s 
Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

$ which ruby
ruby is /usr/bin/ruby

$ ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
```

It looks like a recent cleanup may have removed the function `boot_path_plist_present`, I grepped the `homebrew-services` and could not find a reference. Or is this function defined in another package?

**Comment by Jacobfaib** [comment]
Output of `brew doctor`
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/jacobfaibussowitsch/NoSync/petscpackages/bin/pnetcdf-config
  /Users/jacobfaibussowitsch/NoSync/petscpackages/bin/nc-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  six
  protobuf
```

**Comment by Jacobfaib** [comment]
The following commit `cea6c9f5b65e9d85779ac65c2600f508df5f6b93` is to [blame here](https://github.com/Homebrew/homebrew-services/commit/cea6c9f5b65e9d85779ac65c2600f508df5f6b93#diff-642a732918ee1aeca833e8380816320040a75eb97db5c2743e56e5ad71fc3626R86)

**Comment by rcrews** [comment]
Good work on this @Jacobfaib. I came here to report this, and I see you've already done a great job.

**Comment by ralphjsmit** [comment]
I have the same error message. Just spent half an hour debugging this and reinstalling everything. Thanks Jacobfaib, now I know that there's nothing wrong with my installation 😌

**Comment by pgrenaud** [comment]
Quick and dirty hotfix to make things work in the meantime:

```
cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services
git reset --hard 5f2fe01
```

**Comment by devasghar** [comment]
Call it sloppy but simple commented out the line for now. 
`#boot_path_plist_present? || user_path_plist_present?`
