### ISSUE TITLE
Error: undefined method `timed?' for #<Homebrew::Service:0x00007f8e68cb04c8>

### ISSUE THREAD

**Issue by lokesh1729** [Homebrew/homebrew-services#413]
```
Error: undefined method `timed?' for #<Homebrew::Service:0x00007f8e68cb04c8>
Did you mean?  tainted?
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:42:in `timed?'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:176:in `to_hash'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:17:in `map'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:17:in `services_list'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/list.rb:13:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:86:in `services'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

This error started occurring when I install mongodb.

**Comment by djoproject** [comment]
Hello @SMillerDev, I tried the fix you proposed.  It fixes the `timed` method issue.  But there is at least another missing method:

```
Error: undefined method `cron' for #<Homebrew::Service:0x00007fe5dd190008>
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:196:in `to_hash'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:17:in `map'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:17:in `services_list'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/list.rb:13:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:86:in `services'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

Thank you for your work.

**Comment by Raptorify** [comment]
for now you can just revert to an older commit like this

`git checkout 6aaf037f5eb0399c97a3068908697e1565963762`

**Comment by SMillerDev** [comment]
It's actually fixed in the latest brew release, no need to revert anything.
