### ISSUE TITLE
Error: undefined local variable or method `datadir' for #<Homebrew::Service:0x00007fe014124340>

### ISSUE THREAD

**Issue by sagunshre** [Homebrew/homebrew-services#431]
Got this error while installing percona-server and after installation when executing `brew services list`.
```
Error: undefined local variable or method `datadir' for #<Homebrew::Service:0x00007fe014124340>
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/percona-server.rb:196:in `block in <class:PerconaServer>'
/usr/local/Homebrew/Library/Homebrew/service.rb:278:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/service.rb:278:in `timed?'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:42:in `timed?'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:176:in `to_hash'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:17:in `map'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:17:in `services_list'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/list.rb:13:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:90:in `services'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

**Comment by SMillerDev** [comment]
https://github.com/Homebrew/homebrew-core/pull/92294 will fix this, it's an issue in the formula

**Comment by 5u9** [comment]
```bash
Error: undefined method `zero?' for nil:NilClass
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:205:in `operational_status'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:180:in `to_hash'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:17:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:17:in `services_list'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/list.rb:13:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:90:in `services'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
https://github.com/Homebrew/homebrew-core/pull/92294 was merged
