### ISSUE TITLE
`brew services` yields undefined method under Linux

### ISSUE THREAD

**Issue by selfagency** [Homebrew/homebrew-services#434]
I'm running an Ubuntu-based distro on WSL2. I know that's not officially supported, but it is running `systemd`. Either way, if it's not supported, it should ideally fail gracefully with a notification and not just poop the proverbial bed.

```
03:47:21 PM ⏱️ 3s » brew services
Error: undefined method `zero?' for nil:NilClass
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:205:in `operational_status'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:180:in `to_hash'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:17:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:17:in `services_list'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/list.rb:13:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:90:in `services'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

**Comment by SMillerDev** [comment]
I think I have an idea what this is coming from. Could you post the output of `brew services info --all`?

**Comment by selfagency** [comment]
same

```
brew services info --all
Error: undefined method `zero?' for nil:NilClass
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:205:in `operational_status'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:180:in `to_hash'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/info.rb:13:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/info.rb:13:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:94:in `services'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

**Comment by selfagency** [comment]
ok, so it turns out i wasn't launching into genie properly and that's why i was getting the above error (tho it should probably tell me that i'm not running systemd instead of throwing that error).

however, now i'm getting a different error:

```
10:11:28 AM » sudo brew services start postgresql@11
Unknown command verb .
Error: Failure while executing; `/usr/bin/systemctl '' daemon-reload` exited with 1.
```

**Comment by SMillerDev** [comment]
Try running that command manually because clearly your systemd doesn't work well.
