### ISSUE TITLE
Error: undefined method `length' for nil:NilClass

### ISSUE THREAD

**Issue by zourdyzou** [Homebrew/homebrew-services#454]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.3.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: d603fd6426ddae27327bb51afb085653eb2d84a7
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a0885e2756dadadb0ab223b69cc435fd6513f8f9
Core tap last commit: 42 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: dodeca-core 64-bit zen
Clang: N/A
Git: 2.25.1 => /bin/git
Curl: 7.68.0 => /bin/curl
Kernel: Linux 5.13.0-30-generic x86_64 GNU/Linux
OS: Ubuntu 20.04.3 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: 2.7.0
glibc: N/A
gcc@5: N/A
xorg: N/A
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  php@7.4
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Before I installed the httpd package on my local machine it works just charm like this:
```
php@7.4       started zourdyzou ~/.config/systemd/user/homebrew.php@7.4.service
postgresql@12 started zourdyzou ~/.config/systemd/user/homebrew.postgresql@12.service
redis         started zourdyzou ~/.config/systemd/user/homebrew.redis.service
unbound       unknown           /home/linuxbrew/.linuxbrew/opt/unbound/homebrew.unbound.service
```
but after I installed `httpd` and then start it using `brew services start httpd`:
it logged like this
Error: undefined method `length' for nil:NilClass
```
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/list.rb:33:in `block in print_table'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/list.rb:33:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/list.rb:33:in `print_table'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/list.rb:18:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:90:in `services'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

even though I did not start it or trying to stop it, it fires the same logged, please I need your guidance and advice. thank you :)

### What happened (include all command output)?

Before I installed the httpd package on my local machine it works just charm like this:
```
php@7.4       started zourdyzou ~/.config/systemd/user/homebrew.php@7.4.service
postgresql@12 started zourdyzou ~/.config/systemd/user/homebrew.postgresql@12.service
redis         started zourdyzou ~/.config/systemd/user/homebrew.redis.service
unbound       unknown           /home/linuxbrew/.linuxbrew/opt/unbound/homebrew.unbound.service
```
but after I installed `httpd` and then start it using `brew services start httpd`:
it logged like this
Error: undefined method `length' for nil:NilClass
```
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/list.rb:33:in `block in print_table'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/list.rb:33:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/list.rb:33:in `print_table'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/list.rb:18:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:90:in `services'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

even though I did not start it or trying to stop it, it fires the same logged, please I need your guidance and advice. thank you :)

### What did you expect to happen?

I expect to list the services just fine

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
[I] ⋊> ~/xxxx on master ⨯ brew update                                                                                                                                                                    12:02:18
Already up-to-date.
[I] ⋊> ~/xxxx on master ⨯ brew doctor                                                                                                                                                                    12:02:28
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  php@7.4
```

**Comment by SMillerDev** [comment]
What happens when you stop it again?

**Comment by zourdyzou** [comment]
it works just charm

**Comment by zourdyzou** [comment]
```
[I] ⋊> ~/p/website-nextjs on fix/QuoteText-improvement/dev-4993 ◦ brew info --json httpd                                                                                                                   15:29:30
[
  {
    "name": "httpd",
    "full_name": "httpd",
    "tap": "homebrew/core",
    "oldname": "httpd24",
    "aliases": [
      "apache-httpd",
      "apache2"
    ],
    "versioned_formulae": [

    ],
    "desc": "Apache HTTP server",
    "license": "Apache-2.0",
    "homepage": "https://httpd.apache.org/",
    "versions": {
      "stable": "2.4.52",
      "head": null,
      "bottle": true
    },
    "urls": {
      "stable": {
        "url": "https://dlcdn.apache.org/httpd/httpd-2.4.52.tar.bz2",
        "tag": null,
        "revision": null
      }
    },
    "revision": 0,
    "version_scheme": 0,
    "bottle": {
      "stable": {
        "rebuild": 0,
        "root_url": "https://ghcr.io/v2/homebrew/core",
        "files": {
          "arm64_monterey": {
            "cellar": "/opt/homebrew/Cellar",
            "url": "https://ghcr.io/v2/homebrew/core/httpd/blobs/sha256:7c71a42a41693093015c11813cd3ec9e714f303884afde9bde61b3eb86f2fbae",
            "sha256": "7c71a42a41693093015c11813cd3ec9e714f303884afde9bde61b3eb86f2fbae"
          },
          "arm64_big_sur": {
            "cellar": "/opt/homebrew/Cellar",
            "url": "https://ghcr.io/v2/homebrew/core/httpd/blobs/sha256:2bda2c7798b135b519882bd010bc2b4c8b6fb243c69046713639b22cff689400",
            "sha256": "2bda2c7798b135b519882bd010bc2b4c8b6fb243c69046713639b22cff689400"
          },
          "monterey": {
            "cellar": "/usr/local/Cellar",
            "url": "https://ghcr.io/v2/homebrew/core/httpd/blobs/sha256:6a35059e2c3f69635ac6035c0a638030a1038cc62e648604ab53b4a280a88ba8",
            "sha256": "6a35059e2c3f69635ac6035c0a638030a1038cc62e648604ab53b4a280a88ba8"
          },
          "big_sur": {
            "cellar": "/usr/local/Cellar",
            "url": "https://ghcr.io/v2/homebrew/core/httpd/blobs/sha256:59ee7e0491e7a79a8844b05d0f4075d9b76b707190e6f229b84f763b58b9728a",
            "sha256": "59ee7e0491e7a79a8844b05d0f4075d9b76b707190e6f229b84f763b58b9728a"
          },
          "catalina": {
            "cellar": "/usr/local/Cellar",
            "url": "https://ghcr.io/v2/homebrew/core/httpd/blobs/sha256:af1a311706c4eb1adb63b2179e2677e305f49ec346e74c3a29e60fe9fa8e5d60",
            "sha256": "af1a311706c4eb1adb63b2179e2677e305f49ec346e74c3a29e60fe9fa8e5d60"
          },
          "x86_64_linux": {
            "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
            "url": "https://ghcr.io/v2/homebrew/core/httpd/blobs/sha256:6d602ea4372d756c6ffb622373c5daa750ddb79d65818e4fa686070025b7f8ae",
            "sha256": "6d602ea4372d756c6ffb622373c5daa750ddb79d65818e4fa686070025b7f8ae"
          }
        }
      }
    },
    "keg_only": false,
    "keg_only_reason": null,
    "bottle_disabled": false,
    "options": [

    ],
    "build_dependencies": [

    ],
    "dependencies": [
      "apr",
      "apr-util",
      "brotli",
      "libnghttp2",
      "openssl@1.1",
      "pcre",
      "libxml2",
      "zlib"
    ],
    "recommended_dependencies": [

    ],
    "optional_dependencies": [

    ],
    "uses_from_macos": [
      "libxml2",
      "zlib"
    ],
    "requirements": [

    ],
    "conflicts_with": [

    ],
    "caveats": "DocumentRoot is $(brew --prefix)/var/www.\n\nThe default ports have been set in $(brew --prefix)/etc/httpd/httpd.conf to 8080 and in\n$(brew --prefix)/etc/httpd/extra/httpd-ssl.conf to 8443 so that httpd can run without sudo.\n",
    "installed": [
      {
        "version": "2.4.52",
        "used_options": [

        ],
        "built_as_bottle": true,
        "poured_from_bottle": true,
        "runtime_dependencies": [
          {
            "full_name": "ncurses",
            "version": "6.3",
            "declared_directly": false
          },
          {
            "full_name": "readline",
            "version": "8.1.2",
            "declared_directly": false
          },
          {
            "full_name": "zlib",
            "version": "1.2.11",
            "declared_directly": true
          },
          {
            "full_name": "libxml2",
            "version": "2.9.12",
            "declared_directly": true
          },
          {
            "full_name": "gettext",
            "version": "0.21",
            "declared_directly": false
          },
          {
            "full_name": "util-linux",
            "version": "2.37.4",
            "declared_directly": false
          },
          {
            "full_name": "apr",
            "version": "1.7.0",
            "declared_directly": true
          },
          {
            "full_name": "ca-certificates",
            "version": "2022-02-01",
            "declared_directly": false
          },
          {
            "full_name": "openssl@1.1",
            "version": "1.1.1m",
            "declared_directly": true
          },
          {
            "full_name": "expat",
            "version": "2.4.5",
            "declared_directly": false
          },
          {
            "full_name": "sqlite",
            "version": "3.37.2",
            "declared_directly": false
          },
          {
            "full_name": "mawk",
            "version": "1.3.4-20200120",
            "declared_directly": false
          },
          {
            "full_name": "m4",
            "version": "1.4.19",
            "declared_directly": false
          },
          {
            "full_name": "libtool",
            "version": "2.4.6",
            "declared_directly": false
          },
          {
            "full_name": "unixodbc",
            "version": "2.3.9",
            "declared_directly": false
          },
          {
            "full_name": "apr-util",
            "version": "1.6.1",
            "declared_directly": true
          },
          {
            "full_name": "brotli",
            "version": "1.0.9",
            "declared_directly": true
          },
          {
            "full_name": "libnghttp2",
            "version": "1.46.0",
            "declared_directly": true
          },
          {
            "full_name": "bzip2",
            "version": "1.0.8",
            "declared_directly": false
          },
          {
            "full_name": "pcre",
            "version": "8.45",
            "declared_directly": true
          }
        ],
        "installed_as_dependency": false,
        "installed_on_request": true
      }
    ],
    "linked_keg": "2.4.52",
    "pinned": false,
    "outdated": false,
    "deprecated": false,
    "deprecation_date": null,
    "deprecation_reason": null,
    "disabled": false,
    "disable_date": null,
    "disable_reason": null
  }
]

```

**Comment by SMillerDev** [comment]
Oops, I meant `brew services info httpd --json`. Sorry about that.

**Comment by zourdyzou** [comment]
Hey @SMillerDev I just changed the environment to use dpkg and it is working fine right now, I will close this issue immediately
