### ISSUE TITLE
Recent commit breaks `brew services` on MacOS 10.15.7 Catalina

### ISSUE THREAD

**Issue by chroche** [Homebrew/homebrew-services#531]
Hi,

I understand that MacOS 10.15 is not supported by Homebrew. Just want to report that recent commit #https://github.com/Homebrew/homebrew-services/commit/0c1b711ee5deebd5835fa55585574af959197c65 seems to break the `brew services` commands on MacOS 10.15.7 Catalina:
```bash
> brew services list
Error: undefined method `launchd_service_path' for #<Formulary::FormulaNamespace2a79eb9124f52e7c9f81636ea5bd236c::Rubberband:0x00007fbc3e2c7ef8>
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:58:in `service_file'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:92:in `plist?'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:12:in `select'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:12:in `available_services'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formulae.rb:17:in `services_list'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/list.rb:13:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:102:in `services'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```
Things work fine when reverting to the prior version:
```bash
> cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services
> git checkout 0c1b711^
Previous HEAD position was 0c1b711 Formula wrapper: work without plist_options
HEAD is now at b802596 Merge pull request #517 from Homebrew/revert-512-master
> brew services list
Name           Status User File
dnscrypt-proxy none   root
unbound        none
```

**Comment by SMillerDev** [comment]
Then your brew is outdated.

**Comment by chroche** [comment]
Yes sorry, I think that was the reason. Case closed.
