### ISSUE TITLE
Error starting service

### ISSUE THREAD

**Issue by fgsch** [Homebrew/homebrew-services#608]
```
$ brew services start autoraise
Error: undefined method `plist_startup' for #<Formula autoraise (stable) /opt/homebrew/Library/Taps/dimentium/homebrew-autoraise/autoraise.rb>
Did you mean?  plist_name
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:71:in `service_startup?'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:280:in `service_load'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:122:in `block in start'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:97:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:97:in `start'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/start.rb:12:in `run'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:130:in `services'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

And

```
$ brew config
HOMEBREW_VERSION: 4.2.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: ff899e5b3ff6731208564ef502db237e2627e8ba
Last commit: 6 days ago
Core tap JSON: 24 Dec 10:39 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /opt/homebrew/bin/nvim
HOMEBREW_MAKE_JOBS: 14
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 14-core 64-bit dunno
Clang: 15.0.0 build 1500
Git: 2.43.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.2.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
Rosetta 2: false
```

**Comment by fgsch** [comment]
Looks like this might be the formula and not homebrew after all.
