### ISSUE TITLE
Error: uninitialized constant Homebrew::Service

### ISSUE THREAD

**Issue by lamkuan** [Homebrew/homebrew-services#696]
<img width="795" alt="截圖 2024-07-14 22 58 35" src="https://github.com/user-attachments/assets/1f72428e-19eb-4f6b-bf62-7e5c16d7f94a">

**Comment by kytta** [comment]
I am experiencing a similar issue with [Backrest](https://github.com/garethgeorge/backrest) (provided in a [third-party tap](https://github.com/garethgeorge/homebrew-backrest-tap))

## What I'm doing

```sh
$ brew services restart garethgeorge/backrest-tap/backrest
```

```
Error: uninitialized constant Homebrew::Service
Warning: Removed Sorbet lines from backtrace!
/opt/homebrew/Library/Homebrew/formula.rb:1264:in `service'
/opt/homebrew/Library/Homebrew/formula.rb:1235:in `plist_name'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:49:in `service_name'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:211:in `status_output_success_type'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:104:in `loaded?'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/restart.rb:21:in `block in run'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/restart.rb:20:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/restart.rb:20:in `run'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:135:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:95:in `<main>'
If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/homebrew/homebrew-services/issues/new
```

<details>
<summary>with <code>--debug --verbose</code></summary>

```
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading backrest
Error: uninitialized constant Homebrew::Service
/opt/homebrew/Library/Homebrew/formula.rb:1264:in `service'
/opt/homebrew/Library/Homebrew/formula.rb:1235:in `plist_name'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11481/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:49:in `service_name'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:211:in `status_output_success_type'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:104:in `loaded?'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/restart.rb:21:in `block in run'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/restart.rb:20:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/restart.rb:20:in `run'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:135:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:95:in `<main>'
If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/homebrew/homebrew-services/issues/new
```

</details>

## `brew doctor`

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  schildichat

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  python-packaging
```

None of the packages above should matter here, as they're not dependencies of this Formula

## `brew config`

```
HOMEBREW_VERSION: 4.3.9-154-gb9da669
ORIGIN: https://github.com/Homebrew/brew
HEAD: b9da669ef25c7da0757f5ae1d418985b19efb321
Last commit: 14 minutes ago
Core tap HEAD: 25c2eae0b65332a1496be01e3ea968f631e373df
Core tap last commit: 35 minutes ago
Core tap JSON: 14 Jul 14:58 UTC
Core cask tap HEAD: 358947238dd8946bafd9ffca2d036b2aaa57a4f3
Core cask tap last commit: 49 minutes ago
Core cask tap JSON: 14 Jul 14:58 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT: set
HOMEBREW_BAT_THEME: OneHalfDark
HOMEBREW_BROWSER: open
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 30
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 7
HOMEBREW_EDITOR: micro
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_NO_INSTALL_CLEANUP: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.45.2 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 13.6.7-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
Rosetta 2: false
```

**Comment by kytta** [comment]
It is also worth mentioning that every `brew services` command causes this, including the one without any arguments

**Comment by SMillerDev** [comment]
See also https://github.com/Homebrew/homebrew-core/issues/177327

**Comment by horseson2018** [comment]
> See also [Homebrew/homebrew-core#177327](https://github.com/Homebrew/homebrew-core/issues/177327)

So what should I do? brew update?

**Comment by HIIgor** [comment]
same error。

**Comment by tianmingxing** [comment]
Warning: Calling `brew services'. This command needs to be refactored, as it is written in a style that is deprecated! Use inherits from `Homebrew::AbstractCommand' ( see https://docs.brew.sh/External-Commands ) instead.
Please report this issue to the Homebrew/homebrew-services tap, or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:9

**Comment by tianmingxing** [comment]
It's worked:
```bash
cd /usr/local/Homebrew/Library/Taps/homebrew/
rm -rf homebrew-services
brew tap homebrew/services
```

**Comment by livingston0318** [comment]
> It's worked:
> 
> cd /usr/local/Homebrew/Library/Taps/homebrew/
> rm -rf homebrew-services
> brew tap homebrew/services

works for me, really thx
