### ISSUE TITLE
Error: uninitialized constant Homebrew::Service

### ISSUE THREAD

**Issue by NeoZion** [Homebrew/homebrew-services#778]
```
➜  ~ brew update
==> Updating Homebrew...
Updated 1 tap (homebrew/cask).
==> New Casks
follow@nightly
➜  ~ brew services stop mysql
Warning: Calling `brew services'. This command needs to be refactored, as it is written in a style that is deprecated! Use inherits from `Homebrew::AbstractCommand' ( see https://docs.brew.sh/External-Commands ) instead.
Please report this issue to the Homebrew/homebrew-services tap, or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:9

Error: uninitialized constant Homebrew::Service
/usr/local/Homebrew/Library/Homebrew/formulary.rb:396:in `block in load_formula_from_api'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:285:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:285:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:285:in `load_formula_from_api'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:969:in `load_from_api'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:962:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:570:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:1016:in `factory'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:113:in `services'
/usr/local/Homebrew/Library/Homebrew/brew.rb:96:in `public_send'
/usr/local/Homebrew/Library/Homebrew/brew.rb:96:in `<main>'
If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/homebrew/homebrew-services/issues/new
```

**Comment by MikeMcQuaid** [comment]
Run `brew update-reset` and check if `brew config` or `brew doctor` says you're using an unofficial mirror that may be outdated.
