### ISSUE TITLE
Calling `brew services'. This command needs to be refactored, as it is written in a style that is deprecated! Use inherits from `Homebrew::AbstractCommand' ( see https://docs.brew.sh/External-Commands ) instead.

### ISSUE THREAD

**Issue by ad1095445** [Homebrew/homebrew-services#835]
`Please report this issue to the Homebrew/homebrew-services tap, or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:9

Error: uninitialized constant Homebrew::Service
/opt/homebrew/Library/Homebrew/formulary.rb:396:in `block in load_formula_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:285:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:285:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:285:in `load_formula_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:939:in `load_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:932:in `klass'
/opt/homebrew/Library/Homebrew/formulary.rb:567:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:980:in `factory'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:89:in `services'
/opt/homebrew/Library/Homebrew/brew.rb:97:in `public_send'
/opt/homebrew/Library/Homebrew/brew.rb:97:in `<main>'
If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  `https://github.com/homebrew/homebrew-services/issues/new`

I run "brew services start syncthing",but something wrong, this is the details .

**Comment by ZhongRuoyu** [comment]
What's the output of `git -C "$(brew --repo homebrew/services)" show`? It's very likely that the `homebrew/services` tap is outdated, in which case you need to run `brew update` to update it.

**Comment by ad1095445** [comment]
> 的输出是什么？该 tap 很可能已过时，在这种情况下，您需要运行来更新它。`git -C "$(brew --repo homebrew/services)" show``homebrew/services``brew update`

Thank you bro,finally I install syncthing without brew,and it's work well ,maybe i should update my brew and try again,but it's already work.

**Comment by ChainJ** [comment]
Updating new version mac with M1 chips may cause this problem.
I solved it by doing this:
```
mv -f /opt/homebrew/Library/Taps/homebrew/homebrew-services /opt/homebrew/Library/Taps/homebrew/homebrew-services-bak
brew tap homebrew/services
```
tapping new tool may help.

**Comment by SMillerDev** [comment]
> Updating new version mac with M1 chips may cause this problem.

It will not, but having an outdated brew install will, and your command solves that part by retapping

**Comment by fuyz** [comment]
卸载并重新安装 homebrew/services 插件，以此来修复可能存在的配置问题：
```
brew untap homebrew/services

brew tap homebrew/services
````
